# Generated by Django 6.0.2 on 2026-02-06 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='state',
            field=models.CharField(choices=[('P', 'Pending'), ('C', 'Completed'), ('I', 'In Progress')], default='P', max_length=2),
        ),
    ]
