# Generated by Django 6.0.2 on 2026-02-19 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_task_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Procesos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='task',
            old_name='description',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='task_from',
            new_name='reportado_por',
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_to',
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('B', 'Baja'), ('M', 'Media'), ('A', 'Alta')], default='M', max_length=2),
        ),
        migrations.AlterField(
            model_name='task',
            name='state',
            field=models.CharField(choices=[('P', 'Pendiente'), ('C', 'Completado'), ('E', 'En espera')], default='P', max_length=2),
        ),
        migrations.AddField(
            model_name='task',
            name='proceso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.procesos'),
            preserve_default=False,
        ),
    ]
