# Generated by Django 6.0.2 on 2026-02-19 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_procesos_rename_description_task_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='solucion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
